[package]
name = "spotify-tui"
description = "A terminal user interface for Spotify"
homepage = "https://github.com/Rigellute/spotify-tui"
repository = "https://github.com/Rigellute/spotify-tui"
keywords = ["spotify", "tui", "cli"]
categories = ["command-line-utilities"]
version = "0.1.0"
authors = ["Rigellute <rigellute@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspotify = "0.6.0"
tui = "0.6.2"
termion = "1.5.3"
failure = "0.1.5"
